jwtRules:
  - issuer: "https://auth-dev.learnhub.com/"
    jwksUri: "https://auth-dev.learnhub.com/.well-known/jwks.json"
    outputPayloadToHeader: x-token-payload
    forwardOriginalToken: true
    audiences:
      - api.learnhub.com
      - https://api.dev.learnhub.local/api/
